/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 my.glb -T 
Files: my.glb [1.89MB] > /home/monika/Desktop/Ankit_Dhiman/my_portfolio/public/models/my-transformed.glb [304.08KB] (84%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function My(props) {
  const { scene } = useGLTF('/models/my-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Root} />
      <skinnedMesh geometry={nodes['tripo_node_4a2a40ed-7890-4d83-83f3-a7e614e515e0'].geometry} material={materials['tripo_material_4a2a40ed-7890-4d83-83f3-a7e614e515e0']} skeleton={nodes['tripo_node_4a2a40ed-7890-4d83-83f3-a7e614e515e0'].skeleton} />
    </group>
  )
}

useGLTF.preload('/models/my-transformed.glb')
